[project]
name = "easy-memory"
version = "0.1.0"
description = "Long-term memory for AI Agents"
authors = [
    { name = "Leo", email = "wang_workstaion@163.com" }
]
readme = "README.md"
license = "Apache-2.0"

requires-python = ">=3.12"
dependencies = [
    "azure-core>=1.41.0",
    "boto3>=1.43.19",
    "cassandra-driver>=3.30.0",
    "chromadb>=1.5.9",
    "databricks-sql-connector>=4.2.6",
    "elasticsearch>=9.4.1",
    "faiss-cpu>=1.14.2",
    "fastembed>=0.8.0",
    "google-cloud-aiplatform>=1.154.0",
    "google-genai>=2.7.0",
    "groq>=1.4.0",
    "httpx>=0.28.1",
    "langchain-core>=1.4.0",
    "litellm>=1.86.2",
    "mysql-connector-python>=9.7.0",
    "ollama>=0.6.2",
    "pinecone>=9.0.1",
    "psycopg>=3.3.4",
    "pydantic>=2.13.4",
    "pytz>=2026.2",
    "qdrant-client>=1.18.0",
    "redis>=8.0.0",
    "spacy>=3.8.14",
    "sqlalchemy>=2.0.50",
    "supabase>=2.30.1",
    "together>=2.16.0",
    "turbopuffer>=2.2.0",
    "upstash-vector>=0.8.0",
    "xai-sdk>=1.15.0",
]
